name: Node Backend application

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: cd backend-server
    - run: npm install
    - name: Analysing the code with eslint
      run: npm run lint
    - name: Tests and Coverage
      run: npm run test
